#!/bin/bash

#load functions and variables
source "$HOME/pi-ware-pyqt5/func/api" || echo "failed to source $HOME/pi-ware-pyqt5/func/api"

#Check if connected to internet
while [[ "$(wget -q --spider http://google.com)" -eq 1 ]]
do
  echo "I couldn't detect an internet connection! Trying again..."
  sleep 2
done

#If loop ends, User online
#Check for updates
echo "Checking for updates..."
if [ "$(cat $PW_PREFIX/share/pi-ware-pyqt5/version)" != "$LAST_COMMIT" ] || [ "$1" == "--force" ]; then
  if [ "$1" == "--force" ]; then
    echo "Force updating pi-ware"
  else
    echo "Updating Pi-Ware..."
  fi
  cd $HOME
  rm -rf $HOME/pi-ware-pyqt5/
  git clone "$PW_REPO" $HOME/pi-ware-pyqt5
  rm -rf $PW_PREFIX/share/pi-ware-pyqt5/version
  cd $HOME/pi-ware-pyqt5
  echo $(git rev-parse main) > "$PW_PREFIX/share/pi-ware-pyqt5/version"
  bash install
  cd $HOME
  echo "Update complete, Closing in 5 seconds..."
  sleep 5
  exit 0
else
  echo "Pi-Ware is currently up-to-date."
  sleep 2
  exit 1
fi
